### ISSUE TITLE
Visibility change

### ISSUE THREAD

**Issue by stwsimon** [benwalch/powermailext#1]
Hi.

We're trying this extension, just to create an input field if someone chooses "other" from a select field, but not having success with the visibility toggle.

We're not using any custom templates, just the standard powermail templates.  Other than including the static template and configuring the fields in the form (which we've done as per the guide), do we need to do anything else (including view helpers, etc)?

Thank you

Simon

**Comment by benwalch** [comment]
Hi. 

Thank you for trying this extension.

There are a few things to consider:
- jQuery Library loaded in the frontend is required. make sure jquery is loaded properly
  (described in https://github.com/bendash/powermailext#general)
- in the partials, you have to include the viewhelper which adds the data- attributes
  insert '{namespace pmext=WorldDirect\Powermailext\ViewHelpers}' at the top of your fluid template file
  (described in https://github.com/bendash/powermailext#general)  powermailext automatically overrides the partials root path in typoscript setup to achieve this.
- use this viewhelper to render the data- attributes javascript needs for its visibility handling.
  insert '{pmext:Validation.ContainerDataAttributes(field:field)}' in the opening tag of the container which holds the field
  (described in https://github.com/bendash/powermailext#javascript-visibility-handling)
- follow the example and check if it works
  (https://github.com/bendash/powermailext#example)
