### ISSUE TITLE
TYPO3 7.6 Compatibility

### ISSUE THREAD

**Issue by Hobokens** [benwalch/powermailext#6]
Hi,
are you planning to update the extension. That would be great. I just installed it with v7.6.2 and didn't get any errors. But it doesn't seem to work.

Regards
Hobokens

**Comment by sevenflip** [comment]
Same question here, is there any possibility to push this to T3 7.6.x / powermail 3.x asap?

**Comment by claude27** [comment]
Try this (only working with TYPO3 7.6 and without garanty,!):
[powermailext-76.tar.gz](https://github.com/benwalch/powermailext/files/813545/powermailext-76.tar.gz)

**Comment by benwalch** [comment]
I am planning to update it, will make v8 compatibility as soon as possible

**Comment by benwalch** [comment]
i just pushed an update for typo3 v8. should work with v7.6 but have not tested yet
